name: py-aiogram-taro-bot
services:
  nats:
    image: nats:latest
    entrypoint: /nats-server -js
    ports:
      - "4222:4222"
    volumes:
      - ./nats/data:/data

  redis:
    image: redis:latest
    volumes:
      - ./redis_data:/root/redis

  postgres:
    image: postgres:16
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./docker/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  bot:
    build:
      context: .
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
      nats:
        condition: service_started
    command: sh /service/docker/startup.sh
    ports:
      - "8000:8000"