"""new rules on column user_id in table buys

Revision ID: 0d5a9294c529
Revises: a37a71e40604
Create Date: 2024-09-30 17:03:52.457013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d5a9294c529'
down_revision: Union[str, None] = 'a37a71e40604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('buys_user_id_fkey', 'buys', type_='foreignkey')
    op.create_foreign_key(None, 'buys', 'users', ['user_id'], ['id'], ondelete='SET DEFAULT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'buys', type_='foreignkey')
    op.create_foreign_key('buys_user_id_fkey', 'buys', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
