"""added column inv_number to table users

Revision ID: 6d43ee9ceadc
Revises: 1ba6603c94c8
Create Date: 2024-09-26 12:41:24.373701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d43ee9ceadc'
down_revision: Union[str, None] = '1ba6603c94c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('inv_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'inv_number')
    # ### end Alembic commands ###
