"""new rules2 on column user_id in table buys

Revision ID: 9cee919c586c
Revises: 0d5a9294c529
Create Date: 2024-09-30 17:08:17.918761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cee919c586c'
down_revision: Union[str, None] = '0d5a9294c529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('buys', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('buys_user_id_fkey', 'buys', type_='foreignkey')
    op.create_foreign_key(None, 'buys', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'buys', type_='foreignkey')
    op.create_foreign_key('buys_user_id_fkey', 'buys', 'users', ['user_id'], ['id'], ondelete='SET DEFAULT')
    op.alter_column('buys', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
