"""create invoices table

Revision ID: a37a71e40604
Revises: 6d43ee9ceadc
Create Date: 2024-09-29 17:36:40.831295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a37a71e40604'
down_revision: Union[str, None] = '6d43ee9ceadc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DATE(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'inv_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('inv_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('invoices')
    # ### end Alembic commands ###
