"""changes default free_cards from 3 to 0

Revision ID: ae5b19d7f43a
Revises: 53ce8607ba29
Create Date: 2024-10-04 23:14:44.254506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae5b19d7f43a'
down_revision: Union[str, None] = '53ce8607ba29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
